import type { QuestionList } from '@/types/question';

export const questions: QuestionList = {
  questions: [
    {
      id: 1,
      text: 'What is the output of `typeof NaN`?',
      options: ["'number'", "'NaN'", "'undefined'", "'object'"],
      correctOptionIndex: 0,
    },
    {
      id: 2,
      text: 'Which operator checks for both value and type equality?',
      options: ['==', '===', '=', '!='],
      correctOptionIndex: 1,
    },
    {
      id: 3,
      text: 'What is the result of `2 + "2"`?',
      options: ['4', "'22'", 'NaN', 'Error'],
      correctOptionIndex: 1,
    },
    {
      id: 4,
      text: 'What is the result of `2 - "2"`?',
      options: ['4', "'22'", '0', 'NaN'],
      correctOptionIndex: 2,
    },
    {
      id: 5,
      text: 'Which keyword creates a block-scoped variable?',
      options: ['var', 'let', 'global', 'window'],
      correctOptionIndex: 1,
    },
    {
      id: 6,
      text: 'What is the value of `Boolean("")`?',
      options: ['true', 'false', 'undefined', 'null'],
      correctOptionIndex: 1,
    },
    {
      id: 7,
      text: 'Which array method adds an element to the end?',
      options: ['push()', 'pop()', 'shift()', 'unshift()'],
      correctOptionIndex: 0,
    },
    {
      id: 8,
      text: 'What does `[] == ![]` evaluate to?',
      options: ['true', 'false', 'undefined', 'Error'],
      correctOptionIndex: 0,
    },
    {
      id: 9,
      text: 'What is the result of `NaN === NaN`?',
      options: ['true', 'false', 'undefined', 'Error'],
      correctOptionIndex: 1,
    },
    {
      id: 10,
      text: 'Which function creates a JSON string from an object?',
      options: [
        'JSON.parse()',
        'JSON.toString()',
        'JSON.stringify()',
        'JSON.convert()',
      ],
      correctOptionIndex: 2,
    },
    {
      id: 11,
      text: 'What is the scope of a variable declared with `var`?',
      options: ['Block', 'Function', 'Global only', 'Module'],
      correctOptionIndex: 1,
    },
    {
      id: 12,
      text: 'Which statement immediately exits a function?',
      options: ['break', 'exit', 'return', 'continue'],
      correctOptionIndex: 2,
    },
    {
      id: 13,
      text: 'What is the result of `typeof null`?',
      options: ["'null'", "'undefined'", "'object'", "'number'"],
      correctOptionIndex: 2,
    },
    {
      id: 14,
      text: 'Which creates a new array with results of calling a function on every element?',
      options: ['forEach()', 'map()', 'filter()', 'reduce()'],
      correctOptionIndex: 1,
    },
    {
      id: 15,
      text: 'What is the result of `0.1 + 0.2 === 0.3`?',
      options: ['true', 'false', 'undefined', 'NaN'],
      correctOptionIndex: 1,
    },
    {
      id: 16,
      text: 'What keyword refers to the object from which a method was called?',
      options: ['self', 'super', 'this', 'caller'],
      correctOptionIndex: 2,
    },
    {
      id: 17,
      text: 'Which is NOT a primitive type in JavaScript?',
      options: ['String', 'Number', 'Object', 'Boolean'],
      correctOptionIndex: 2,
    },
    {
      id: 18,
      text: 'What does `Array.isArray({})` return?',
      options: ['true', 'false', 'undefined', 'Error'],
      correctOptionIndex: 1,
    },
    {
      id: 19,
      text: 'What is the output of `console.log(x); var x = 5;`?',
      options: ['5', 'undefined', 'Error', 'null'],
      correctOptionIndex: 1,
    },
    {
      id: 20,
      text: 'Which event occurs when the user clicks an HTML element?',
      options: ['onchange', 'onmouseover', 'onclick', 'onmouseclick'],
      correctOptionIndex: 2,
    },
    {
      id: 21,
      text: 'What is the result of `!!1`?',
      options: ['true', 'false', '1', 'undefined'],
      correctOptionIndex: 0,
    },
    {
      id: 22,
      text: 'Which method removes the last element of an array?',
      options: ['shift()', 'unshift()', 'pop()', 'push()'],
      correctOptionIndex: 2,
    },
    {
      id: 23,
      text: 'How do you check if a property "x" exists in object "o"?',
      options: ['o.has("x")', '"x" in o', 'o.contains("x")', 'exist(o.x)'],
      correctOptionIndex: 1,
    },
    {
      id: 24,
      text: 'What is `Promise.resolve(5)`?',
      options: ['5', 'Promise { 5 }', 'undefined', 'Function'],
      correctOptionIndex: 1,
    },
    {
      id: 25,
      text: 'Which loop is guaranteed to run at least once?',
      options: ['for', 'while', 'do...while', 'foreach'],
      correctOptionIndex: 2,
    },
    {
      id: 26,
      text: 'What is the result of `+"10"`?',
      options: ["'10'", '10', 'NaN', 'Error'],
      correctOptionIndex: 1,
    },
    {
      id: 27,
      text: 'What does `bind()` return?',
      options: [
        'The result of the function',
        'A new function',
        'undefined',
        'The context',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 28,
      text: 'What is the output of `1 < 2 < 3`?',
      options: ['true', 'false', 'undefined', 'Error'],
      correctOptionIndex: 0,
    },
    {
      id: 29,
      text: 'What is the output of `3 > 2 > 1`?',
      options: ['true', 'false', 'undefined', 'Error'],
      correctOptionIndex: 1,
    },
    {
      id: 30,
      text: 'Which method converts a string to a floating-point number?',
      options: ['parseInt()', 'parseFloat()', 'Number()', 'toFloat()'],
      correctOptionIndex: 1,
    },
    {
      id: 31,
      text: 'What corresponds to the "Event Loop" mechanism?',
      options: [
        'DOM structure',
        'Concurrency model',
        'CSS Parsing',
        'Memory Heap',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 32,
      text: 'Which is used to handle exceptions?',
      options: ['try...catch', 'if...else', 'switch', 'check...error'],
      correctOptionIndex: 0,
    },
    {
      id: 33,
      text: 'What value is `undefined + 1`?',
      options: ['1', 'NaN', 'undefined', 'Error'],
      correctOptionIndex: 1,
    },
    {
      id: 34,
      text: 'Which method combines two arrays?',
      options: ['append()', 'attach()', 'concat()', 'merge()'],
      correctOptionIndex: 2,
    },
    {
      id: 35,
      text: 'What does `Object.keys(obj)` return?',
      options: ['Values', 'Keys array', 'String of keys', 'Object clone'],
      correctOptionIndex: 1,
    },
    {
      id: 36,
      text: 'What will `console.log(typeof [])` output?',
      options: ["'array'", "'object'", "'list'", "'undefined'"],
      correctOptionIndex: 1,
    },
    {
      id: 37,
      text: 'How do you declare an async function?',
      options: [
        'function asyncName()',
        'async function name()',
        'await function()',
        'promise function()',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 38,
      text: 'What is the result of `5 == "5"`?',
      options: ['true', 'false', 'undefined', 'Error'],
      correctOptionIndex: 0,
    },
    {
      id: 39,
      text: 'Which operator raises a number to a power?',
      options: ['^', '**', 'pow', '^^'],
      correctOptionIndex: 1,
    },
    {
      id: 40,
      text: 'What is passed to `setTimeout` as the first argument?',
      options: ['Duration', 'Callback function', 'Event', 'Scope'],
      correctOptionIndex: 1,
    },
    {
      id: 41,
      text: 'What is a "Closure"?',
      options: [
        'Function bundled with lexical environment',
        'A library',
        'A loop type',
        'An object method',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 42,
      text: 'Which keyword stops the execution of a loop?',
      options: ['stop', 'halt', 'break', 'end'],
      correctOptionIndex: 2,
    },
    {
      id: 43,
      text: 'What does `eval("2 + 2")` return?',
      options: ["'2 + 2'", '4', 'NaN', 'Error'],
      correctOptionIndex: 1,
    },
    {
      id: 44,
      text: 'Which symbol is used for template literals?',
      options: ["'", '"', '`', '-'],
      correctOptionIndex: 2,
    },
    {
      id: 45,
      text: 'What is the default value of an uninitialized variable?',
      options: ['null', 'undefined', '0', 'false'],
      correctOptionIndex: 1,
    },
    {
      id: 46,
      text: 'How many primitive data types are there in modern JS?',
      options: ['5', '6', '7', '8'],
      correctOptionIndex: 2,
    },
    {
      id: 47,
      text: 'Which method returns the character at a specific index?',
      options: ['charAt()', 'getChar()', 'slice()', 'index()'],
      correctOptionIndex: 0,
    },
    {
      id: 48,
      text: 'What does destructuring allow you to do?',
      options: [
        'Delete objects',
        'Unpack values from arrays/objects',
        'Create structures',
        'Compile code',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 49,
      text: 'What is the result of `null == undefined`?',
      options: ['true', 'false', 'Error', 'null'],
      correctOptionIndex: 0,
    },
    {
      id: 50,
      text: 'Which saves data in the browser with no expiration?',
      options: ['sessionStorage', 'cookies', 'localStorage', 'cache'],
      correctOptionIndex: 2,
    },
    // TypeScript Questions
    {
      id: 51,
      text: 'What is the "unknown" type in TypeScript?',
      options: [
        'Same as any',
        'Type-safe counterpart of any',
        'A string type',
        'An error type',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 52,
      text: 'Which utility type creates a type with all properties set to optional?',
      options: ['Required<T>', 'Partial<T>', 'Readonly<T>', 'Pick<T>'],
      correctOptionIndex: 1,
    },
    {
      id: 53,
      text: 'What does the "keyof" operator do?',
      options: [
        'Returns values of an object',
        'Returns union of keys of a type',
        'Creates a new key',
        'Validates a key',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 54,
      text: 'How do you define a type alias?',
      options: ['interface X {}', 'type X = {}', 'class X {}', 'def X {}'],
      correctOptionIndex: 1,
    },
    {
      id: 55,
      text: 'Which is NOT a valid access modifier in TypeScript classes?',
      options: ['public', 'private', 'protected', 'internal'],
      correctOptionIndex: 3,
    },
    {
      id: 56,
      text: 'What is the return type of a function that never returns?',
      options: ['void', 'undefined', 'never', 'null'],
      correctOptionIndex: 2,
    },
    {
      id: 57,
      text: 'Can interfaces extend other interfaces?',
      options: ['Yes', 'No', 'Only classes', 'Only types'],
      correctOptionIndex: 0,
    },
    {
      id: 58,
      text: 'What does result in "const x: [string, number]"?',
      options: ['Array', 'Tuple', 'Object', 'Union'],
      correctOptionIndex: 1,
    },
    {
      id: 59,
      text: 'Which utility type removes types from a union?',
      options: ['Exclude<T, U>', 'Extract<T, U>', 'Omit<T, K>', 'Pick<T, K>'],
      correctOptionIndex: 0,
    },
    {
      id: 60,
      text: 'How to make a property readonly in an interface?',
      options: ['static prop', 'const prop', 'readonly prop', 'final prop'],
      correctOptionIndex: 2,
    },
    {
      id: 61,
      text: 'What is "Type Assertion"?',
      options: [
        'Checking type at runtime',
        'Telling compiler strictly what type to treat as',
        'Casting error',
        'Creating new type',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 62,
      text: 'Which symbol is used for non-null assertion?',
      options: ['?', '!', '??', '&'],
      correctOptionIndex: 1,
    },
    {
      id: 63,
      text: 'What is the equivalent of "any" but safer?',
      options: ['void', 'never', 'unknown', 'object'],
      correctOptionIndex: 2,
    },
    {
      id: 64,
      text: 'How do you denote an optional parameter in a function?',
      options: ['param?', 'param!', 'optional param', '?param'],
      correctOptionIndex: 0,
    },
    {
      id: 65,
      text: 'Which type represents "either A or B"?',
      options: [
        'Intersection (A & B)',
        'Union (A | B)',
        'Tuple [A, B]',
        'Enum',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 66,
      text: 'Does TypeScript exist at runtime?',
      options: [
        'Yes, fully',
        'No, it compiles to JS',
        'Partially',
        'Only in Node.js',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 67,
      text: 'What is an "Enum"?',
      options: [
        'A function',
        'A set of named constants',
        'A loop',
        'A type alias',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 68,
      text: 'Which utility constructs a type with properties K from T?',
      options: ['Omit<T, K>', 'Pick<T, K>', 'Record<K, T>', 'Partial<T>'],
      correctOptionIndex: 1,
    },
    {
      id: 69,
      text: 'What is the "void" type used for?',
      options: [
        'Function returning nothing',
        'Empty object',
        'Null value',
        'Error',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 70,
      text: 'What check allows narrowing a union type?',
      options: ['Type Guard', 'Type Cast', 'Type Alias', 'Type Query'],
      correctOptionIndex: 0,
    },
    {
      id: 71,
      text: 'What does `Omit<T, K>` do?',
      options: [
        'Picks keys',
        'Constructs type by picking all from T then removing K',
        'Makes keys optional',
        'Makes keys required',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 72,
      text: 'How to define an index signature?',
      options: [
        '[key: string]: any',
        '{key: string}',
        '(key: string)',
        '<key: string>',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 73,
      text: 'Can abstract classes be instantiated directly?',
      options: ['Yes', 'No', 'Only in strict mode', 'Only if empty'],
      correctOptionIndex: 1,
    },
    {
      id: 74,
      text: 'Which command compiles TypeScript code?',
      options: ['node', 'npm', 'tsc', 'ts-node'],
      correctOptionIndex: 2,
    },
    {
      id: 75,
      text: 'What does generic `<T>` represent?',
      options: [
        'A specific type',
        'A type variable (placeholder)',
        'A template string',
        'Transformation',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 76,
      text: 'Is `interface` supported in standard JavaScript?',
      options: ['Yes', 'No', 'Yes in ES6', 'Yes in Node'],
      correctOptionIndex: 1,
    },
    {
      id: 77,
      text: 'What applies to `readonly` array?',
      options: ['Can push', 'Can pop', 'Cannot mutate', 'Can sort'],
      correctOptionIndex: 2,
    },
    {
      id: 78,
      text: 'Which keyword is used for inheritance in classes?',
      options: ['implements', 'extends', 'inherits', 'super'],
      correctOptionIndex: 1,
    },
    {
      id: 79,
      text: 'What is "structural typing" in TS often called?',
      options: ['Duck typing', 'Goose typing', 'Bird typing', 'Strict typing'],
      correctOptionIndex: 0,
    },
    {
      id: 80,
      text: 'Can you use "this" as a type?',
      options: ['Yes', 'No', 'Only in interfaces', 'Only in abstract classes'],
      correctOptionIndex: 0,
    },
    {
      id: 81,
      text: 'What is `ReturnType<T>`?',
      options: [
        'Returns strict type',
        'Extracts return type of function type T',
        'Returns void',
        'Returns any',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 82,
      text: 'Are typescript decorators stable usage?',
      options: [
        'Yes, fully standard',
        'No, experimental feature',
        'Deprecated',
        'Removed',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 83,
      text: 'What type is `x` if `let x = "hello"` (no annotation)?',
      options: ['any', 'string', 'unknown', 'object'],
      correctOptionIndex: 1,
    },
    {
      id: 84,
      text: 'What is the top type in TypeScript?',
      options: ['Object', 'any', 'unknown', 'void'],
      correctOptionIndex: 2,
    },
    {
      id: 85,
      text: 'Can you implement multiple interfaces?',
      options: ['Yes', 'No', 'Only one', 'Max 2'],
      correctOptionIndex: 0,
    },
    // Node.js Questions
    {
      id: 86,
      text: 'Which is NOT a global object in Node.js?',
      options: ['process', 'window', 'global', 'Buffer'],
      correctOptionIndex: 1,
    },
    {
      id: 87,
      text: 'What pattern does Node.js use for concurrency?',
      options: [
        'Multi-threading',
        'Single-threaded Event Loop',
        'Blocking I/O',
        'Parallelism',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 88,
      text: 'Which module is used for file operations?',
      options: ['fs', 'file', 'path', 'io'],
      correctOptionIndex: 0,
    },
    {
      id: 89,
      text: 'What is `process.nextTick()`?',
      options: [
        'Executes after current operation completes',
        'Executes after timeout',
        'Executes next loop',
        'Executes immediately',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 90,
      text: 'What is the default module system in Node.js (historically)?',
      options: ['AMD', 'ESM', 'CommonJS', 'UMD'],
      correctOptionIndex: 2,
    },
    {
      id: 91,
      text: "Which global variable holds current module's directory?",
      options: ['__filename', '__dirname', 'cwd', 'path'],
      correctOptionIndex: 1,
    },
    {
      id: 92,
      text: 'How do you emit an event in Node?',
      options: ['fire()', 'dispatch()', 'emit()', 'send()'],
      correctOptionIndex: 2,
    },
    {
      id: 93,
      text: 'Which stream type is `fs.createReadStream`?',
      options: ['Writable', 'Readable', 'Duplex', 'Transform'],
      correctOptionIndex: 1,
    },
    {
      id: 94,
      text: 'What does package.json `scripts` do?',
      options: [
        'Define dependencies',
        'Define shortcuts for CLI commands',
        'Configures DB',
        'Compiles code',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 95,
      text: 'What is the purpose of `Buffer` class?',
      options: [
        'Handle binary data',
        'Buffer video',
        'Cache strings',
        'Store logs',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 96,
      text: 'Which function runs immediately but asynchronously?',
      options: ['setImmediate', 'setTimeout(0)', 'process.nextTick', 'async()'],
      correctOptionIndex: 0,
    },
    {
      id: 97,
      text: 'Is `require()` synchronous or asynchronous?',
      options: ['Synchronous', 'Asynchronous', 'Both', 'Promise-based'],
      correctOptionIndex: 0,
    },
    {
      id: 98,
      text: 'What does `npm init` do?',
      options: [
        'Installs node',
        'Creates package.json',
        'Starts server',
        'Updates npm',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 99,
      text: 'What is the popular web framework for Node?',
      options: ['Django', 'Laravel', 'Express', 'Spring'],
      correctOptionIndex: 2,
    },
    {
      id: 100,
      text: 'What object is used to handle HTTP requests?',
      options: [
        'http.IncomingMessage',
        'http.ClientRequest',
        'http.Server',
        'http.Agent',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 101,
      text: 'How to handle unhandled promise rejections globally?',
      options: [
        'process.on("unhandledRejection")',
        'try-catch',
        'window.onerror',
        'error event',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 102,
      text: 'Which core module provides path utilities?',
      options: ['fs', 'path', 'url', 'os'],
      correctOptionIndex: 1,
    },
    {
      id: 103,
      text: 'What is `exports` in a module?',
      options: [
        'A function',
        'Reference to module.exports',
        'Global var',
        'A string',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 104,
      text: 'Which is used to create a child process?',
      options: [
        'child_process.fork()',
        'process.create()',
        'new Process()',
        'system()',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 105,
      text: 'Does Node.js support multi-threading natively for JS execution?',
      options: [
        'Yes',
        'No (Single threaded)',
        'Yes via Worker Worker Threads',
        'Yes via Clusters',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 106,
      text: 'What is the event emitter method `once` do?',
      options: [
        'Listens forever',
        'Listens once then removes listener',
        'Emits once',
        'Errors once',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 107,
      text: 'What does `NODE_ENV=production` typically do?',
      options: [
        'Installs devDeps',
        'Enables optimizations/logging changes',
        'Deletes files',
        'Nothing',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 108,
      text: 'Which module is used for cryptography?',
      options: ['hash', 'crypto', 'security', 'cipher'],
      correctOptionIndex: 1,
    },
    {
      id: 109,
      text: 'What represents an open file in Node?',
      options: ['File ID', 'File String', 'File Descriptor', 'File Path'],
      correctOptionIndex: 2,
    },
    {
      id: 110,
      text: '`util.promisify` does what?',
      options: [
        'Callback func -> Promise func',
        'Promise -> Callback',
        'Sync -> Async',
        'Async -> Sync',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 111,
      text: 'What is a "middleware" in Express?',
      options: [
        'Database driver',
        'Function with access to req/res/next',
        'Front-end code',
        'A template',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 112,
      text: 'Which method stops the Node process?',
      options: ['end()', 'stop()', 'process.exit()', 'kill()'],
      correctOptionIndex: 2,
    },
    {
      id: 113,
      text: 'Where are global npm packages installed?',
      options: ['local node_modules', 'System directory', 'Cache', 'Temp'],
      correctOptionIndex: 1,
    },
    {
      id: 114,
      text: 'What is "libuv"?',
      options: [
        'JS Engine',
        'C library for Async I/O',
        'Package manager',
        'Test runner',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 115,
      text: 'How to access command line arguments?',
      options: ['process.argv', 'process.arg', 'cmd.args', 'sys.argv'],
      correctOptionIndex: 0,
    },
    {
      id: 116,
      text: 'Streams are instances of which class?',
      options: ['EventEmitter', 'Process', 'Buffer', 'String'],
      correctOptionIndex: 0,
    },
    {
      id: 117,
      text: 'What is the default port for HTTP?',
      options: ['80', '443', '3000', '8080'],
      correctOptionIndex: 0,
    },
    {
      id: 118,
      text: 'Which memory heap does V8 use?',
      options: [
        'Stack only',
        'Generational (New/Old space)',
        'Flat',
        'Circular',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 119,
      text: 'How to read a file synchronously?',
      options: [
        'fs.read()',
        'fs.readFileSync()',
        'fs.readSync()',
        'await fs.read()',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 120,
      text: 'Does Node.js imply blocking or non-blocking by default?',
      options: ['Blocking', 'Non-blocking', 'Both', 'Depends on OS'],
      correctOptionIndex: 1,
    },
    // Advanced JS Questions
    {
      id: 121,
      text: 'What does `Object.is(NaN, NaN)` return?',
      options: ['true', 'false', 'undefined', 'Error'],
      correctOptionIndex: 0,
    },
    {
      id: 122,
      text: 'What is a "Generator" function syntax?',
      options: [
        'function* name()',
        'function name()*',
        'gen function()',
        'async* name()',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 123,
      text: 'What keyword yields control in a Generator?',
      options: ['return', 'await', 'yield', 'pause'],
      correctOptionIndex: 2,
    },
    {
      id: 124,
      text: 'What does the `Reflect` API provide?',
      options: [
        'DOM access',
        'Methods for interceptable JS operations',
        'Mirroring UI',
        'Copying objects',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 125,
      text: 'Difference between `Map` and `Object` keys?',
      options: [
        'No difference',
        'Map keys can be any type, Object keys strings/symbols',
        'Object keys are sorted',
        'Map is slower',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 126,
      text: 'What is "Hoisting"?',
      options: [
        'Moving code to bottom',
        'Moving declarations to top of scope',
        'Uploading files',
        'Looping',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 127,
      text: 'Are `let` and `const` hoisted?',
      options: [
        'No',
        'Yes, but in Temporal Dead Zone (TDZ)',
        'Yes fully initialized',
        'Only const',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 128,
      text: 'What is a "Proxy" object?',
      options: [
        'Server proxy',
        'Object that intercepts operations on another object',
        'Copy of object',
        'JSON parser',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 129,
      text: 'What is the purpose of `WeakMap`?',
      options: [
        'Map with weak validation',
        'Map holding weak references to keys (garbage collectable)',
        'Small map',
        'Map for weak types',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 130,
      text: 'Can arrow functions be constructors?',
      options: ['Yes', 'No', 'Only with new', 'If exported'],
      correctOptionIndex: 1,
    },
    {
      id: 131,
      text: 'What is "Currying"?',
      options: [
        'Spicing code',
        'Transforming func(a,b) to func(a)(b)',
        'Async execution',
        'Binding this',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 132,
      text: 'Which creates a microtask?',
      options: [
        'setTimeout',
        'setImmediate',
        'Promise.then',
        'requestAnimationFrame',
      ],
      correctOptionIndex: 2,
    },
    {
      id: 133,
      text: 'What does `Object.freeze()` do?',
      options: [
        'Prevents modification of properties',
        'Makes object invisible',
        'Deletes object',
        'Pauses object',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 134,
      text: 'Is `Object.freeze()` shallow or deep?',
      options: ['Shallow', 'Deep', 'Both', 'Neither'],
      correctOptionIndex: 0,
    },
    {
      id: 135,
      text: 'What does `?.` operator do? (Optional Chaining)',
      options: [
        'Ternary op',
        'Short-circuits returning undefined if null/undefined',
        'Bitwise op',
        'Logical OR',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 136,
      text: 'What does `??` operator do? (Nullish Coalescing)',
      options: [
        'Returns right if left is null/undefined',
        'Returns right if left is falsy',
        'Returns boolean',
        'Power op',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 137,
      text: 'What is the "prototype" of an Object created with `{}`?',
      options: [
        'null',
        'Object.prototype',
        'Array.prototype',
        'Function.prototype',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 138,
      text: 'What does `Object.create(null)` do?',
      options: [
        'Creates empty object with NO prototype',
        'Creates null',
        'Error',
        'Standard object',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 139,
      text: 'What is "Tail Call Optimization"?',
      options: [
        'Optimizing usage of tails',
        'Reusing stack frame for last call',
        'Removing recursion',
        'Faster loops',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 140,
      text: 'Can you use `await` at top level?',
      options: [
        'Never',
        'Yes, in modules (Top-level await)',
        'Only in functions',
        'Only in Node',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 141,
      text: 'Which set maintains insertion order?',
      options: ['Set', 'HashSet', 'WeakSet', 'All Sets'],
      correctOptionIndex: 0,
    },
    {
      id: 142,
      text: 'Output of `console.log(1 + "1" - 1)`?',
      options: ['10', '11', '1', 'NaN'],
      correctOptionIndex: 0,
    },
    {
      id: 143,
      text: 'Output of `["1", "5", "11"].map(parseInt)`?',
      options: ['[1, 5, 11]', '[1, NaN, 3]', 'Error', '[1, 5, NaN]'],
      correctOptionIndex: 1,
    },
    {
      id: 144,
      text: 'What defines a "Pure Function"?',
      options: [
        'No side effects, same input=same output',
        'No arguments',
        'Async function',
        'Fast function',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 145,
      text: 'What is "Memoization"?',
      options: [
        'Writing notes',
        'Caching results of function calls',
        'Memory leak',
        'Compression',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 146,
      text: 'Which big int literal is valid?',
      options: ['123n', '123b', '123i', 'Big(123)'],
      correctOptionIndex: 0,
    },
    {
      id: 147,
      text: 'What is the Global Execution Context?',
      options: [
        'First context created',
        'Last context',
        'Error context',
        'Function context',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 148,
      text: 'What does `Array.from()` do?',
      options: [
        'Creates array from iterable/array-like',
        'Finds item',
        'Sorts array',
        'Deletes array',
      ],
      correctOptionIndex: 0,
    },
    {
      id: 149,
      text: 'Does `const` make contents immutable?',
      options: [
        'Yes',
        'No, only the binding is immutable',
        'Depends on type',
        'Only for objects',
      ],
      correctOptionIndex: 1,
    },
    {
      id: 150,
      text: 'What happens if you access a property on `undefined`?',
      options: ['undefined', 'null', 'TypeError', '0'],
      correctOptionIndex: 2,
    },
  ],
};
